### ISSUE TITLE
Error Redmine 3.0.4.stable.14445

### ISSUE THREAD

**Issue by vsc55** [yossiedri/Redmine-Admin-Monitor-Plugin#8]
Clicking MONITOR ALERTS opens a page with a 500 error.

Log Error:

Started GET "/admin_monitor_alerts?conditions=false" for 192.168.0.1 at 2015-07-21 19:08:25 +0200
Processing by AdminMonitorAlertsController#index as HTML
  Parameters: {"conditions"=>"false"}
  Current user: user (id=6)
DEPRECATION WARNING: #paginate with a Symbol and/or find options is depreceted and will be removed. Use a scope instead. (called from deprecated_paginate at /opt/redmine/redmine-3.0/lib/redmine/pagination.rb:133)
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.5ms)

NoMethodError (undefined method `update_or_create' for #<Class:0x0000000320f898>):
  activerecord (4.2.3) lib/active_record/dynamic_matchers.rb:26:in`method_missing'
  plugins/redmine_admin_monitor/lib/redmine_admin_monitor/patches/application_controller_patch.rb:19:in `render_500'
  activesupport (4.2.3) lib/active_support/rescuable.rb:80:in`call'
  activesupport (4.2.3) lib/active_support/rescuable.rb:80:in `rescue_with_handler'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:15:in`rescue_with_handler'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:32:in `rescue in process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in`block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in`instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in`process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in`dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in`block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in`dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in`block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in`serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in`call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in`call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in`call'
  actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in`call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in`context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in`call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in`call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in`run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in`call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in`call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in`call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in`call'
  railties (4.2.3) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.3) lib/rails/railtie.rb:194:in`method_missing'
  /usr/lib64/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
  /usr/lib64/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in`accept_and_process_next_request'
  /usr/lib64/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib64/ruby/vendor_ruby/phusion_passenger/request_handler.rb:414:in`block (3 levels) in start_threads'
  /usr/lib64/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

**Comment by amizhang** [comment]
Same issue we met.... I used the other branch, but still doesn't work..
